language: python
os:
  - linux
  - osx
#  - windows
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install pyinstaller
install:
  - make
script:
  - pytest
branches:
  only:
    - master
    - devel
#deploy:
#   skip_cleanup: true
#	provider: releases
#	api_key: "GITHUB OAUTH TOKEN"
#	file:
#       - "dist/py2fits.exe"
#	on:
#		tags: true