language: python
os:
  - linux
  - osx
#  - windows
python:
  - "2.7"
  - "3.6"
#addons:
#  homebrew:
#    packages:
#      - python==$(TRAVIS_PYTHON_VERSION)
before_install:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#      brew install python
#    fi
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install pyinstaller
install:
  - make
script:
  - pytest
branches:
  only:
    - master
    - devel
#deploy:
#  skip_cleanup: true
#	 provider: releases
#	 api_key: "GITHUB OAUTH TOKEN"
#	 file:
#    - "dist/fits2txt"
#	 on:
#    tags: true
